import time
from groq import Groq
from configs.settings import (
    GROQ_API_KEY,
    GROQ_MODEL,
    GROQ_TIMEOUT,
    GROQ_TEMPERATURE,
    GROQ_ENABLED,
)

_client = None

SYSTEM_PROMPT = """You are an ultra-fast speech-to-text post-processor for a live voice typing tool.
Your job is to clean and refine the raw transcript generated by automatic speech recognition (Whisper).

Instructions:
1. Fix phonetic speech recognition mistakes, homophones, typos, and misspelled words based on context.
2. Add proper punctuation (periods, commas, question marks, apostrophes), capitalization, and formatting.
3. Fix minor stuttering or duplicate words caused by hesitation while preserving the speaker's original intent and meaning.
4. Keep technical terms, acronyms, code words, and numbers formatted naturally.
5. NEVER answer questions, summarize, or engage in conversation.
6. CRITICAL: Output ONLY the cleaned transcript text. Do NOT include greetings, preamble, quotes around the output, or explanations."""


def get_client() -> Groq:
    """Lazily initializes and returns the Groq client with timeout."""
    global _client
    if _client is None:
        if not GROQ_API_KEY:
            return None
        _client = Groq(
            api_key=GROQ_API_KEY,
            timeout=GROQ_TIMEOUT,
            max_retries=0,  # Fast fail for real-time voice typing
        )
    return _client


def clean_transcript(raw_text: str) -> str:
    """
    Cleans raw Whisper transcript using Groq LLM.
    Falls back to raw_text immediately on timeout, network error, or if disabled.
    """
    if not raw_text or not raw_text.strip():
        return raw_text

    if not GROQ_ENABLED:
        return raw_text

    if not GROQ_API_KEY or GROQ_API_KEY.strip() == "":
        print("[LLM Cleaner] GROQ_API_KEY not set. Using raw Whisper transcript.")
        return raw_text

    client = get_client()
    if client is None:
        return raw_text

    start_time = time.perf_counter()

    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": raw_text},
            ],
            temperature=GROQ_TEMPERATURE,
            max_tokens=1024,
        )

        cleaned_text = response.choices[0].message.content.strip()
        elapsed = time.perf_counter() - start_time

        # Remove accidental surrounding quotes if model added them
        if (
            len(cleaned_text) >= 2
            and (cleaned_text.startswith('"') and cleaned_text.endswith('"'))
            or (cleaned_text.startswith("'") and cleaned_text.endswith("'"))
        ):
            cleaned_text = cleaned_text[1:-1].strip()

        if cleaned_text:
            print(f"[LLM Cleaner] Cleaned with {GROQ_MODEL} in {elapsed:.2f}s")
            return cleaned_text
        else:
            print("[LLM Cleaner] Groq returned empty output. Using raw transcript.")
            return raw_text

    except Exception as e:
        elapsed = time.perf_counter() - start_time
        print(f"[LLM Cleaner Fallback ({elapsed:.2f}s)] Error: {e}")
        print("[LLM Cleaner Fallback] Reverting to raw Whisper transcript.")
        return raw_text
